version: "3.5"
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins

    ports:
      - 1300:8080
    volumes:
      -  jenkins:/var/jenkins_home
    restart: "on-failure"
    environment:
      - PUID=1000
      - PGID=100
    hostname: jenkins
volumes:
  jenkins:
    external: true
