version: "3"

services:
  wordpress:
     image: wordpress:latest
     volumes:
       - /srv/dev-disk-by-uuid-9712d9e1-ceda-449e-b56e-4d43093c8d6c/MyDrive/apps/wp_moviedb:/var/www/html
     ports:
       - 1305:80
     restart: always
     environment:
       - PUID=1000
       - PGID=100
       - WORDPRESS_DB_HOST=192.168.1.35:1302
       - WORDPRESS_DB_NAME=wp_moviedb
       - WORDPRESS_DB_USER=root
       - WORDPRESS_DB_PASSWORD=ashwin@123
     hostname: wordpress-moviedb
     user: 1000:100
